### ISSUE TITLE
About  "Reference number"

### ISSUE THREAD

**Issue by guysum** [nessgor/fps-hk-qrcode#1]
I tested the project and found some problem about the field "Reference number"
If I input something into "Reference Number" and generate the QR code. And then use my HSBC app to scan, it will pop out "this QR code does not match its designation of Merchant/personal".
If I input nothing in the field "Reference Number", the QR code is workable.
Do you have any idea?

**Comment by nessgor** [comment]
I also face the same problem, but i think this is related to the HSBC app and FPS system.

**Comment by nessgor** [comment]
My electric bill have a FPS QR code, the format is the same as my generator output. It works on HSBC app, I think it is related to the FPS ID, The FPS ID of HK Elec Co. starts with 1 but not 7

**Comment by alexabidri** [comment]
@nessgor Can you explain me more about the issue with HSBC? I could not figure out why when I put reference number, it fails each time.

**Comment by nessgor** [comment]
@guysum @alexabidri If you are going to use the Reference Number field in the FPS QR Code, make sure you have enabled the "Request to Pay" feature for your FPS account. If not, please contact your bank to enable the feature first, or your QR Code will not work as expected.

**Comment by nessgor** [comment]
I have requested my bank to enable the feature and they send me an agreement to sign then after a few working days they will send you the details about how to retrieve the FPS daily transaction report.

**Comment by iamdonwong** [comment]
Anyone how to enable "request to pay"?
I called hsbc and they said there is no such option to enable. They asked me to subscribe to another service which charges 1.8% fee for each transaction.
